package:
   name: mo_aws_earth
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..
git:
  depth: false

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  noarch: python

requirements:
  build:
    - python
    - jinja2
  run:
    - python
    - scipy
    - iris
    - iris_hypothetic >=v0.1.3
    - intake
    - intake_hypothetic >=v0.1.1

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - py.test --verbose

about:
  home: https://github.com/informaticslab/mo-aws-earth
  license: BSD
  license_file: LICENSE
  summary: |
    Tools for working with the Met Office AWS Earth data
